### ISSUE TITLE
How to download MOPEX data from FTP server？

### ISSUE THREAD

**Issue by ChuJinggang** [oreopie/hydro-interpretive-dl#3]
This link（https://www.nws.noaa.gov/ohd/mopex/mo_datasets.htm）has expired，and I have problem（EEISocketClientError 96260）when I try to download from FTP server（ftp://hydrology.nws.noaa.gov）.
Can you tell me how to download data from FTP correctly？Thank for your reply.

**Comment by oreopie** [comment]
You might not be the only one in this situation. There is another repository mentioned here: https://www.researchgate.net/post/Does_anybody_have_access_to_MOPEX_data (I have already included the link of HydroShare link in the README).
